### PR TITLE
README 

### PR DESCRIPTION
**Pull request by Jeong-Hyun-Su**
넣어야할 내용 있으면 피드백 부탁드립니다.

### CODE REVIEW

**Review by minsulee2 — APPROVED** [review]
Please resolve conflict.
LGTM with minor comment

**Comment by Jeong-Hyun-Su** [comment]
We thought about listing and linking our ainize gpt2 models.

**Comment by gkswjdzz** [comment]
LGTM

**Review by gkswjdzz — APPROVED** [review]

**Comment by gkswjdzz** [comment]
Could you start the commit message with a verb such as Update README?

**Pull request merged**
